### ISSUE TITLE
hexo-yuidoc does not work with hexo 3.1.1

### ISSUE THREAD

**Issue by flozz** [hexojs/hexo-yuidoc#1]
Hello,

hewo-yuidoc does not work with hexo 3.1.1: each time I run `hexo generate` it fails to load the plugin:

```
ERROR Plugin load failed: hexo-yuidoc
ReferenceError: hexo is not defined
    at Object.<anonymous> ([...]/test-yui/node_modules/hexo-yuidoc/lib/model.js:9:34)
```

Is there any solution?

**Comment by tomap** [comment]
Indeed, it does not. This plugin is deprecated. 
If you want you can fix it by submiting a PR or Fork it to fix it.
